### PR TITLE
add flag to allow clobbering of existing directories to prevent excep…

### PR DESCRIPTION
**Pull request by connolly**
Allow clobbering of output directory so ISR does not throw an exception when overwriting files. Default is for no clobbering

### CODE REVIEW

**Comment by teweitsai** [comment]
Please ask to merge into `develop` branch instead of `master` branch in PR.

**Comment by connolly** [comment]
moved to develop branch

**Review by teweitsai — APPROVED** [review]
The update looks good!

**Comment by bxin** [comment]
When I tried this in a docker container, I got the following error

> OSError: [Errno 16] Device or resource busy: '/home/lsst/output'

I think this is because the path '/home/lsst/output' is mapped to a path on the local machine.

**Comment by connolly** [comment]
Are you running with the clobber flag set to true when this error occurs and in docker you cant delete the local machine directory?

**Comment by bxin** [comment]
> Are you running with the clobber flag set to true when this error occurs and in docker you cant delete the local machine directory?

That is correct.

**Comment by connolly** [comment]
When you are in the docker container can you remove the directory manually (ie. rm -rf /home/lsst/output)?

**Comment by bxin** [comment]
No. I get the same error.

**Comment by teweitsai** [comment]
If you mount a volume (`/mnt/dir`) from the host machine to a docker container (`/docker/dir`), you can do `rm -rf /docker/dir/*` in the container, but not `rm -rf /docker/dir`. The implementation of `--clobber` may not consider the use of `docker` and do the `shutil.rmtree(outputDir)` directly.

**Pull request merged**
