### PR TITLE
tickets/DM-37442

### PR DESCRIPTION
**Pull request by jbkalmbach**
Change refcat ingestion to use  instead of  to make it easy to move closed loop repos between machines.

### CODE REVIEW

**Comment by suberlak** [comment]
Is the desired effect that now one can run the `imgCloseLoop` on one machine, eg. `scp` that to somewhere else, and expect the `butler` repo to be readable? How has this functionality been tested?

**Comment by jbkalmbach** [comment]
Yeah, exactly. I've been using the `relsymlink` to move closed loop simulations from hyak to the USDF and reading the donut catalogs in from the butler successfully.

**Comment by jbkalmbach** [comment]
It hasn't been a problem for the donut stamps and other output. I think that is because the default data transfer mode in `pipetask run` is `copy` and not `direct`.

**Review by suberlak — APPROVED** [review]
Thanks for the update!

**Review by suberlak — COMMENTED** [review]
All the documentation that I could find is https://pipelines.lsst.io/v/weekly/py-api/lsst.daf.butler.Datastore.html?highlight=relsymlink#lsst.daf.butler.Datastore.ingest , I was wondering how did you decide to use `relsymlink` vs `direct`

**Comment by jbkalmbach** [comment]
I used the command line help docstring to see all the different types and then just guessed based upon the name, haha.

**Pull request merged**
